language: python
python:
  - 3.6.2
install:
  - pip install -r requirements.txt
  - pip install coveralls  
script:
  - nosetests --with-coverage
  - coverage run --source=yummyrecipes tests/*
after_success:
  coveralls
